# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x0b\x64\x65mo_server\"/\n\ractionrequest\x12\x0e\n\x06input1\x18\x01 \x01(\t\x12\x0e\n\x06input2\x18\x02 \x01(\t\"\x1d\n\x0e\x61\x63tionresponse\x12\x0b\n\x03res\x18\x01 \x01(\t2S\n\nFormatData\x12\x45\n\x08\x44oFormat\x12\x1a.demo_server.actionrequest\x1a\x1b.demo_server.actionresponse\"\x00\x42\'\n\x0b\x64\x65mo_serverB\x10\x44\x65moServiceProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\013demo_serverB\020DemoServiceProtoP\001\242\002\003HLW'
  _ACTIONREQUEST._serialized_start=27
  _ACTIONREQUEST._serialized_end=74
  _ACTIONRESPONSE._serialized_start=76
  _ACTIONRESPONSE._serialized_end=105
  _FORMATDATA._serialized_start=107
  _FORMATDATA._serialized_end=190
# @@protoc_insertion_point(module_scope)
